blueprint:
  name: Восход света
  author: sinigamiruyk
  description: 'Скрипт-компаньон для блюпринта автоматизации параболического будильника'
  source_url: https://github.com/devyvorobyov/ha_cercadian_alarm_rus/blob/main/script/light_sunrise.yaml
  domain: script
  homeassistant:
    min_version: 2024.9.0
  input: {}

fields:
  target_kelvin:
    name: Максимальная температура (Кельвины)
    description: Самое холодное значение Кельвинов. Это конечное значение - самый белый свет
    selector:
      color_temp:
        unit: kelvin
    default: 6500
  start_kelvin:
    name: Минимальная температура (Кельвины)
    description: Начальное значение (тёплый свет). Если свет включён, будет использовано текущее значение из состояния светильника, и этот параметр будет проигнорирован
    selector:
      color_temp:
        unit: kelvin
        min: 2500
        max: 6500
    default: 2500
  max_brightness_pct:
    name: Максимальная яркость
    description: Максимальная яркость в процентах, которую нужно достичь к концу выполнения скрипта
    selector:
      number:
        min: 1
        max: 100
        unit_of_measurement: "%"
    default: 80
  alarm_length:
    name: Длительность будильника
    description: Время от начала до конца цикла. Учитывайте это при настройке автоматизации, которая вызывает этот скрипт
    selector:
      number:
        min: 1
        max: 60
        unit_of_measurement: мин
    default: 10
  steps_per_minute:
    name: Шагов в минуту
    description: Количество шагов изменения параметров в минуту
    selector:
      number:
        min: 1
        max: 12
    default: 12
  target_light:
    name: Целевой источник света
    description: Один светильник или группа светильников
    selector:
      entity:
        filter:
          domain: light
  light_timeout:
    name: Таймаут выключения света
    description: Минуты задержки после достижения максимальной яркости перед выключением света. Значение 0 отключает таймаут
    selector:
      number:
        min: 0
        max: 60
        unit_of_measurement: мин
    default: 5

variables:
  steps: '{{ alarm_length * steps_per_minute }}'
  min_brightness: >
    {% if states(target_light) == 'off' %}
      3
    {% else %}
      {{ state_attr(target_light, 'brightness') }}
    {% endif %}
  max_brightness: '{{ max_brightness_pct * 2.55 }}'
  kelvin_step: '{{ (target_kelvin - start_kelvin) / steps }}'
  bright_step: '{{ (max_brightness - min_brightness) / steps }}'
  start_time: '{{ as_timestamp(now()) }}'
  individual_step: '{{ 60 / steps_per_minute }}'

sequence:
  - repeat:
      until:
        - condition: or
          conditions:
            - condition: template
              value_template: '{{ is_state(target_light, ''off'') }}'
            - condition: template
              value_template: '{{ state_attr(target_light, ''brightness'') >= max_brightness }}'
            - condition: template
              value_template: '{{ state_attr(target_light, ''color_temp_kelvin'') >= target_kelvin }}'
            - condition: template
              value_template: '{{ (((as_timestamp(now()) - start_time) / individual_step) | round(0, "ceil")) > steps }}'
      sequence:
        - variables:
            steps_to_now: >
              {{ ((as_timestamp(now()) - start_time) / individual_step) | round(0, "ceil") }}
            brightness: '{{ min_brightness + (bright_step * steps_to_now) | round(0, ''ceil'') }}'
            kelvin: '{{ start_kelvin + (kelvin_step * steps_to_now) }}'
        - delay:
            seconds: '{{ individual_step }}'
        - if:
            - condition: template
              value_template: '{{ not is_state(target_light, ''off'') }}'
          then:
            - data:
                brightness: '{{ brightness }}'
                color_temp_kelvin: '{{ kelvin }}'
              target:
                entity_id: '{{ target_light }}'
              action: light.turn_on
  - if:
      - condition: and
        conditions:
          - condition: template
            value_template: '{{ light_timeout != 0 }}'
          - condition: template
            value_template: '{{ not is_state(target_light, ''off'') }}'
    then:
      - delay:
          minutes: '{{ light_timeout }}'
      - data: {}
        target:
          entity_id: '{{ target_light }}'
        action: light.turn_off

mode: parallel